# Generated by Django 5.1.1 on 2024-09-15 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="close_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 15, 1, 58, 32, 27802, tzinfo=datetime.timezone.utc
                ),
                verbose_name="close date",
            ),
            preserve_default=False,
        ),
    ]
