# Generated by Django 5.1.1 on 2024-09-15 02:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_poll_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="close_date",
            field=models.DateTimeField(
                default=datetime.timedelta(days=1), verbose_name="close date"
            ),
        ),
    ]
