# Generated by Django 5.1.1 on 2024-09-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0008_alter_poll_close_date_alter_poll_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default="dd81a070-7ff4-454a-b634-f8e72d9f9d85",
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
