# Generated by Django 5.1.1 on 2024-09-15 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0009_vote_receipt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("f7b54ec3-a59d-4aeb-a9cd-3b72716cb797"),
                editable=False,
                unique=True,
            ),
        ),
    ]
