# Generated by Django 5.1.1 on 2024-09-15 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0011_poll_open_date_alter_vote_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="hide_poll",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("a3ae29b4-aaef-4b94-97c0-b36f267efc36"),
                editable=False,
                unique=True,
            ),
        ),
    ]
