# Generated by Django 5.1.1 on 2024-09-15 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0012_poll_hide_poll_alter_vote_receipt_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="hide_poll",
            new_name="visible",
        ),
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("eea8ed7f-f27c-4ac5-a672-e1e1a6384b41"),
                editable=False,
                unique=True,
            ),
        ),
    ]
