# Generated by Django 5.1.1 on 2024-09-15 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0013_rename_hide_poll_poll_visible_alter_vote_receipt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("79d4f152-a482-409c-9a1c-9a81926fe200"),
                editable=False,
                unique=True,
            ),
        ),
    ]
