# Generated by Django 5.1.1 on 2024-09-17 07:26

import django.db.models.deletion
import django.utils.timezone
import uuid
import vote.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0015_poll_results_visible_alter_vote_receipt_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_name", models.CharField(max_length=512)),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                ("election_open", models.BooleanField(default=True)),
                (
                    "open_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="open date"
                    ),
                ),
                (
                    "close_date",
                    models.DateTimeField(
                        default=vote.models.get_default_close_date,
                        verbose_name="close date",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("results_visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("a8c7eaa5-00a8-4a8f-9f91-c618d46b4fdd"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("affiliation", models.CharField(max_length=256)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.election"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferences", models.JSONField()),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_id",
                    models.UUIDField(
                        default=uuid.UUID("33766e67-c7a2-48fe-9417-8aad13c9df19"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.election"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "election")},
            },
        ),
    ]
