# Generated by Django 5.1.1 on 2024-09-17 07:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0016_election_alter_vote_receipt_id_candidate_ballot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("3c5a38bc-8998-462b-a9ca-9ee1578aabb0"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="receipt_id",
            field=models.UUIDField(
                default=uuid.UUID("7f2b6d54-2431-417d-b89a-d98a8c75c67d"),
                editable=False,
                unique=True,
            ),
        ),
    ]
