# Generated by Django 5.1.1 on 2024-09-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0017_alter_ballot_receipt_id_alter_vote_receipt_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballot",
            name="receipt_id",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="receipt_id",
        ),
    ]
