# Generated by Django 5.1.1 on 2024-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0018_remove_ballot_receipt_id_remove_vote_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="election_type",
            field=models.CharField(
                choices=[
                    ("IRV", "Instant Runoff Voting"),
                    ("STV", "Single Transferable Vote"),
                    ("PBV", "Preferential Block Voting"),
                ],
                default="IRV",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="number_of_seats",
            field=models.IntegerField(default=1),
        ),
    ]
