# Generated by Django 5.1.3 on 2024-11-09 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0020_election_voting_instructions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ballot",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ballot",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ballot",
            name="voted_at",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="voted_at",
        ),
        migrations.CreateModel(
            name="BallotRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.election"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "election")},
            },
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.poll"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "poll")},
            },
        ),
    ]
